# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a98944ff31a2166a1d3aecc280d4b18cd44376119eea2d3d4998c6ec1130c7178e83a453bd34a04cbe76fb12e9338f189347ec43d4c615049671439e67a296c8

test:
  secret_key_base: 19ea92e8e40fed8363a9e4fac20b039cb55a58e0946d528105e9ab63673faf06b92bade04bd840f7df7147855f2a4fd68b6040b12df9bb8dfc93cffe91afce81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
